# Generated by Django 5.2.4 on 2025-07-05 07:50

import django.db.models.deletion
import houses.definitions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveHouseWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('not_started', 'not_started'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed')], default=houses.definitions.WebsiteProcessingState['NOT_STARTED'], max_length=20)),  # noqa: E501
                ('crawler_class', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_kana', models.CharField(max_length=255, unique=True)),
                ('name_romaji', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('opened_date', models.DateField()),
                ('closed_date', models.DateField(default=None, null=True)  # noqa: DJ001),
                ('last_collected_datetime', models.DateTimeField(blank=True, null=True)  # noqa: DJ001),
                ('last_collection_state', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('timeout', 'timeout')], default=houses.definitions.CrawlerCollectionState['PENDING'], max_length=20)),  # noqa: E501
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_houses', to='houses.livehousewebsite')),  # noqa: E501
            ],
            options={
                'verbose_name': 'Live House',
                'verbose_name_plural': 'Live Houses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_date', models.DateField()),
                ('open_time', models.TimeField()),
                ('start_time', models.TimeField()),
                ('live_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_schedules', to='houses.livehouse')),  # noqa: E501
                ('performers', models.ManyToManyField(blank=True, related_name='performance_schedules', to='performers.performer')),  # noqa: E501
            ],
            options={
                'verbose_name': 'Performance Schedule',
                'verbose_name_plural': 'Performance Schedules',
                'ordering': ['performance_date', 'start_time'],
            },
        ),
    ]
