# Generated by Django 5.2.4 on 2025-07-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_performancescheduleticketpurchaseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceschedule',
            name='performance_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
