# Generated by Django 5.2.4 on 2025-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_performanceschedule_performance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceschedule',
            name='door_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),  # noqa: DJ001
        ),
        migrations.AddField(
            model_name='performanceschedule',
            name='presale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),  # noqa: DJ001
        ),
    ]
