# Generated by Django 5.2.4 on 2025-10-29 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_performanceschedule_door_price_and_more'),
        ('performers', '0004_performersong_youtube_duration_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True, verbose_name='target date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlaylistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.monthlyplaylist')),  # noqa: E501
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performers.performersong')),
            ],
            options={
                'unique_together': {('playlist', 'position')},
            },
        ),
    ]
