# Generated by Django 5.2.4 on 2025-10-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_monthlyplaylist_monthlyplaylistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplaylist',
            name='youtube_channel_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='monthlyplaylist',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='monthlyplaylist',
            name='youtube_playlist_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
