# Generated by Django 5.2.4 on 2025-11-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_monthlyplaylist_youtube_channel_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplaylistentry',
            name='is_spotlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='performancescheduleticketpurchaseinfo',
            name='ticket_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
