# Generated by Django 5.2.4 on 2026-05-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_add_source_url_to_performanceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplaylist',
            name='shorts_youtube_video_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
