# Generated by Django 5.2.4 on 2026-06-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0016_set_club_quattro_crawler_class'),
        ('houses', '0016_set_cyclone_crawler_class'),
        ('houses', '0016_set_shinjuku_face_crawler_class'),
    ]

    operations = [
    ]
