# Generated by Django 5.2.4 on 2025-07-05 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_kana', models.CharField(max_length=255, unique=True)),
                ('name_romaji', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)  # noqa: DJ001),
                ('website', models.URLField(blank=True, max_length=255, null=True)  # noqa: DJ001),
            ],
            options={
                'verbose_name': 'Performer',
                'verbose_name_plural': 'Performers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerformerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roles', models.CharField(blank=True, default='', max_length=255)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='performers.performer')),  # noqa: E501
            ],
            options={
                'verbose_name': 'Performer Member',
                'verbose_name_plural': 'Performer Members',
                'ordering': ['performer__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformerMemberSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('platform_id', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, max_length=255, null=True)  # noqa: DJ001),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='performers.performermember')),  # noqa: E501
            ],
            options={
                'verbose_name': 'Performer Member Social Link',
                'verbose_name_plural': 'Performer Member Social Links',
                'ordering': ['member__performer__name', 'member__name', 'platform'],
            },
        ),
    ]
