# Generated by Django 5.2.4 on 2025-07-05 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformerSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)  # noqa: DJ001),
                ('duration', models.DurationField(blank=True, null=True)  # noqa: DJ001),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='performers.performer')),  # noqa: E501
            ],
            options={
                'verbose_name': 'Performer Song',
                'verbose_name_plural': 'Performer Songs',
                'ordering': ['performer__name', 'title'],
            },
        ),
    ]
