# Generated by Django 5.2.4 on 2025-07-05 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0002_performersong'),
    ]

    operations = [
        migrations.AddField(
            model_name='performermember',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performermember',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='performermembersociallink',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performermembersociallink',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='performersong',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performersong',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PerformerSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=50)),
                ('platform_id', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),  # noqa: DJ001
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='performers.performer')),  # noqa: E501
            ],
            options={
                'abstract': False,
            },
        ),
    ]
