# Generated by Django 5.2.4 on 2025-07-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0003_performermember_created_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performersong',
            name='youtube_duration_seconds',
            field=models.IntegerField(blank=True, null=True)  # noqa: DJ001,
        ),
        migrations.AddField(
            model_name='performersong',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, null=True)  # noqa: DJ001,
        ),
        migrations.AddField(
            model_name='performersong',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='performersong',
            name='youtube_view_count',
            field=models.BigIntegerField(blank=True, null=True)  # noqa: DJ001,
        ),
    ]
